### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by rscohn2** [intelxed/mbuild#7]
Work in progress

https://github.com/rscohn2/mbuild/commit/d303ecba7c99f0ff3c88fd9ec059d8114e734a8a

still some issues with unicode

**Comment by rscohn2** [comment]
Mark,

Can you look at https://github.com/rscohn2/mbuild/tree/py3
It works for your tests for python2, it mostly works for python3, but never exits. If you can explain the logic for detecting when it is done, I could look at it in more detail.

I installed python3 with https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

./Miniconda3-latest-Linux-x86_64.sh -b -p /path/to/install

**Comment by markcharney** [comment]
thanks. The mbuild scripts should exit when the work queue threads shut down. They do that when the work_queue_t object is __del__ deleted.  As part of that I send each thread a message (a special job with t.terminator = True telling it to die, then I join the threads.  I can make a mini-version of that system in python3 and see how it behaves.  

The other thing that goes on at shut-down is we pickle the signatures (hashes) of the command lines and files scanned. I know that code required a lot of changes for python3-ness; I have not fully digested all that you've done there yet.

**Comment by markcharney** [comment]
I took a look and sent a pull request to your fork: #8 

Here's my summary at least for the moment. Maybe someone with a deeper knowledge of python3 shutdown can explain the right thing.  I was trying to terminate the threads in the work_queue.__del__ method. That works in python2.7.x, but not the python3.5.2 that I'm using.

# unlike python2, python3 has a problem shutting down queues and
# threads at the end of the process execution. So we have a few options:

# 1) Daemonic threads:  process can end with them running
#    -> you don't  have to do anything UNLESS you care about leaving lots of threads
#    around in which case you can call del on the object or terminate()

# 2) nonDaemonic threads: process cannot end with them running
#   -> must call terminate()
#   or could manually del the object
#  BUT YOU CANNOT LET SHUTDOWN DEL THE OBJECT BECAUSE
#  IT MIGHT NOT HAPPEN and you won't terminate

**Comment by rscohn2** [comment]
xed builds with py3, but fails in the tests. See below

Using feature/py3 branches in xed and mbuild in rscohn2 fork

[COMMAND     ] gcc      -m64   -o build/examples/xed-dec-print build/examples/xed-dec-print.o build/examples/xed-examples-util.o build/examples/xed-dot.o build/examples/xed-dot-prep.o build/examples/xed-enc-lang.o build/libxed.a  

[STATUS] RUNNING: 0    PENDING: 0    COMPLETED: 19   ERRORS: 0   ELAPSED: 2 secs 
[COMMAND     ] gcc      -m64   -o build/examples/xed-ex-ild2 build/examples/xed-ex-ild2.o build/examples/xed-examples-util.o build/examples/xed-dot.o build/examples/xed-dot-prep.o build/examples/xed-enc-lang.o build/libxed.a  

[XED EXAMPLES] build succeeded
[EXAMPLES BUILD ELAPSED TIME] 3 secs
[STRIPPING] /home/rscohn1/workspaces/xed/build/examples/xed-min
[STRIP CMD] strip  /home/rscohn1/workspaces/xed/build/examples/xed-min
[XED-MIN SIZE] 3513776 = 3.35MB
a bytes-like object is required, not 'str'
(py3mbuild) rscohn1@ubuntu-xenial:~/workspaces/xed$

**Comment by markcharney** [comment]
#13 merged
